### ISSUE TITLE
Specifying custom receiver site

### ISSUE THREAD

**Issue by jpreistad** [Dartspacephysiker/e3doubt#1]
I had trouble specifying a custom receiver site using the "receivers" keyword when initializing the experiment object. It seem like on line 383 in experiment.py, the provided info in the "receivers" keyword is attempteds overwritten, and it chrashes if the provided receiver site name does not match one of the default names. 

I wonder if line 383 just can be removed to fix this?

**Comment by jpreistad** [comment]
Should have provided code to reproduce, here it is:

`import e3doubt`
`exp = e3doubt.Experiment(transmitter=('ski_mod', 67.2,23.7), 
                         receivers=[('ski_mod', 67.2,23.7), ('kai_mod', 66.18,22.54), ('krs_mod', 66.25,25.92)])`

**Comment by Dartspacephysiker** [comment]
Removed the offending line as suggested by jpreistad, and added a more informative error message on line 1260 in `_process_site` method.
